# -*- coding: utf-8 -*-
"""ICP_3_700747025.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6Tsn2aBp0nh3Lt-GUxZCIaaM0lcH4w1
"""

# 1. Create a class Employee and then do the following
# • Create a data member to count the number of Employees
# • Create a constructor to initialize name, family, salary, department
# • Create a function to average salary
# • Create a Fulltime Employee class and it should inherit the properties of Employee class
# • Create the instances of Fulltime Employee class and Employee class and call their member functions.

# Creating a class called 'Employee'
class Employee:
  employee_count = 0

# Declaring and initializing the constructor
  def __init__(self, name, family, salary, department):

        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count = Employee.employee_count + 1

# Creating a function called avg_salary
  def avg_salary(self, emps):
      sum_salary = 0
      for i in emps:
            sum_salary= sum_salary+ i.salary

# Printing the output
      print(sum_salary/len(emps))

# Creating a class called Fulltime_Employee
class Fulltime_Employee(Employee):

      def __init__(self, name, family, salary, department):
         Employee.__init__(self, name, family, salary, department)

list = []
list.append(Employee('Brad', 'Pitt', 30000, 'Supply Chain Management'))
list.append(Employee('Jhonny', 'deep', 40000, 'Human Resources'))

list.append(Fulltime_Employee('Will', 'Smith', 50000, 'Sales'))
list.append(Fulltime_Employee('Leonardo', 'Dicaprio', 60000, 'Research and Development'))

list[0].avg_salary(list)
list[2].avg_salary(list)

# Printing output of an employee count
print(Employee.employee_count)

# 2. Numpy
# Using NumPy create random vector of size 20 having only float in the range 1-20.
# Then reshape the array to 4 by 5
# Then replace the max in each row by 0 (axis=1)
# (you can NOT implement it via for loop)

import numpy as np

# Creating a  random vector that has a  size 20 with floats between 1 and 20
vec = np.random.uniform(1, 20, 20)

# Reshaping the vector to 4 by 5
mat = vec.reshape(4, 5)

# Replace the maximum number in each row by 0
mat[np.arange(4), mat.argmax(axis=1)] = 0

# Printing the output
print(mat)